name = "RLEVectors"
uuid = "17b45ede-fd0d-54ef-b825-8cf9fc64da95"
version = "0.9.3"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "^0.19.4"
Missings = "^0.4.3"
OrderedCollections = "^1.1.0"
Reexport = "^0.2.0"
Requires = "^0.5.2"
StatsBase = "^0.32.0"
julia = "1"
